extType = music
extId = fma
extClass = FmaExtension
extIcon = 
extName = Free Music Archive
extDescription = Stream royalty-free music from freemusicarchive.org
extAuthor = sidharath01
extAuthorUrl = 
extRepoUrl = https://github.com/sidharath01/Music-from-web
extUpdateUrl = https://api.github.com/repos/sidharath01/Music-from-web/releases
